on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

name: Tests
jobs:
  tests:
    name: "test"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm packages
        run: npm run full-install

      - name: Build test sheet
        run: npm run build

      - name: Tests
        run: npm run test
